# Underwriting Engine Architecture Specification
# Risk assessment and underwriting decision engine for insurance applications

service:
  name: underwriting-engine
  version: 1.0.0
  description: Automated and semi-automated underwriting decision engine with ML-based risk assessment
  domain: insurance.underwriting
  type: decision-engine

architecture:
  pattern: rules-engine-with-ml
  style: pipeline
  deployment: containerized
  
service_boundaries:
  responsibilities:
    - Risk assessment and scoring
    - Underwriting rule execution
    - Decision automation
    - Manual review workflow
    - Risk factor analysis
    - Underwriting guideline management
    - ML model inference
    - Decision audit trail
    
  excluded_responsibilities:
    - Policy issuance (handled by policy-service)
    - Premium calculation (handled by rating-engine)
    - Customer communication (handled by notification-service)
    - Document verification (handled by document-service)
    
  bounded_context:
    aggregates:
      - UnderwritingApplication
      - RiskAssessment
      - UnderwritingDecision
      - UnderwritingRule
      
    entities:
      - Application
      - Applicant
      - RiskProfile
      - UnderwritingDecision
      - ReferralCase
      - UnderwritingRule
      - RiskFactor
      
    value_objects:
      - RiskScore
      - DecisionType
      - ReferralReason
      - UnderwritingStatus
      - RiskCategory
      - DecisionConfidence

api:
  rest:
    base_path: /api/v1/underwriting
    endpoints:
      - method: POST
        path: /applications
        description: Submit application for underwriting
        async: true
        sla:
          response_time: 2000ms
          availability: 99.9%
          
      - method: GET
        path: /applications/{applicationId}/decision
        description: Get underwriting decision
        cache: false
        sla:
          response_time: 200ms
          availability: 99.99%
          
      - method: POST
        path: /applications/{applicationId}/review
        description: Submit for manual review
        async: true
        sla:
          response_time: 500ms
          
      - method: PUT
        path: /rules/{ruleId}
        description: Update underwriting rule
        async: false
        sla:
          response_time: 300ms
          
  grpc:
    services:
      - name: UnderwritingService
        methods:
          - AssessRisk
          - GetDecision
          - OverrideDecision
          - GetRiskFactors
          
      - name: RuleManagementService
        methods:
          - CreateRule
          - UpdateRule
          - DisableRule
          - TestRule

async_patterns:
  messaging:
    broker: kafka
    patterns:
      - pattern: event-driven
        events:
          - ApplicationSubmitted
          - RiskAssessmentCompleted
          - DecisionMade
          - ManualReviewRequired
          - DecisionOverridden
          - RuleUpdated
          
      - pattern: pipeline
        pipelines:
          - name: UnderwritingPipeline
            stages:
              - DataValidation
              - RiskDataEnrichment
              - RuleEvaluation
              - MLScoring
              - DecisionConsolidation
              - AuditLogging
            parallel_stages:
              - [RuleEvaluation, MLScoring]
              
      - pattern: circuit-breaker
        services:
          - external_data_providers
          - ml_inference_service
          
  queues:
    - name: underwriting-applications
      type: work
      durability: persistent
      priority_levels: 3
      dead_letter: enabled
      
    - name: manual-review-queue
      type: work
      durability: persistent
      sla: 4_hours
      
    - name: ml-inference-queue
      type: work
      durability: persistent
      batch_size: 100

performance_requirements:
  throughput:
    automated_decisions: 5000/minute
    manual_reviews: 100/minute
    rule_evaluations: 50000/minute
    
  latency:
    automated_decision:
      p50: 200ms
      p95: 1000ms
      p99: 2000ms
    ml_inference:
      p50: 100ms
      p95: 500ms
      p99: 1000ms
      
  scalability:
    horizontal: auto-scaling
    min_instances: 5
    max_instances: 100
    scaling_metric: queue_depth
    
  availability:
    target: 99.95%
    degraded_mode: rule-based-only
    failover: active-passive

decision_engine:
  rule_engine:
    type: drools
    version: 8.0
    rule_format: drl
    
    rule_categories:
      - category: eligibility
        rules:
          - age_limits
          - geographic_restrictions
          - product_eligibility
          
      - category: risk_assessment
        rules:
          - medical_history
          - occupation_risk
          - lifestyle_factors
          - financial_stability
          
      - category: compliance
        rules:
          - regulatory_requirements
          - anti_fraud
          - sanctions_screening
          
  ml_models:
    - name: risk_score_model
      type: gradient_boosting
      version: 2.1.0
      features: 150
      update_frequency: monthly
      
    - name: fraud_detection_model
      type: neural_network
      version: 1.3.0
      features: 200
      update_frequency: weekly
      
    - name: claim_prediction_model
      type: random_forest
      version: 3.0.0
      features: 120
      update_frequency: quarterly
      
  decision_matrix:
    thresholds:
      auto_approve:
        risk_score: "<30"
        confidence: ">0.85"
        
      auto_decline:
        risk_score: ">70"
        confidence: ">0.85"
        
      manual_review:
        risk_score: "30-70"
        confidence: "<0.85"

data_management:
  storage:
    primary:
      type: postgresql
      schema: underwriting
      partitioning: by_date
      
    analytics:
      type: clickhouse
      retention: 2_years
      
    model_store:
      type: mlflow
      backend: s3
      
  external_data:
    providers:
      - name: medical_information_bureau
        type: rest_api
        cache_ttl: 24h
        timeout: 5s
        
      - name: credit_bureau
        type: soap
        cache_ttl: 7d
        timeout: 10s
        
      - name: dmv_records
        type: rest_api
        cache_ttl: 30d
        timeout: 15s
        
  consistency:
    model: strong
    transaction_boundary: application
    
monitoring:
  metrics:
    business:
      - approval_rate
      - decline_rate
      - manual_review_rate
      - average_decision_time
      - rule_hit_rate
      - model_accuracy
      
    technical:
      - rule_execution_time
      - model_inference_time
      - external_api_latency
      - queue_depth
      - error_rate
      
  ml_monitoring:
    - model_drift
    - feature_importance_shift
    - prediction_distribution
    - accuracy_degradation
    
  logging:
    decision_audit:
      enabled: true
      retention: 7_years
      fields:
        - application_id
        - decision
        - risk_score
        - rules_fired
        - model_predictions
        - timestamp
        
  alerts:
    - metric: approval_rate
      threshold: "<40%"
      window: 1h
      severity: warning
      
    - metric: model_accuracy
      threshold: "<0.85"
      window: 1d
      severity: critical
      
    - metric: external_api_failure
      threshold: ">5%"
      window: 5m
      severity: critical

security:
  authentication:
    type: mutual_tls
    certificate_validation: strict
    
  authorization:
    type: attribute_based
    policies:
      - underwriter_can_override
      - analyst_can_view
      - admin_can_configure
      
  data_protection:
    pii_encryption: field_level
    data_masking: enabled
    audit_trail: immutable
    
  compliance:
    standards:
      - HIPAA
      - GDPR
      - SOC2
    audit_frequency: quarterly

integration:
  dependencies:
    internal:
      - service: policy-service
        version: ">=1.0.0"
        communication: async
        
      - service: customer-service
        version: ">=1.0.0"
        communication: grpc
        
      - service: document-service
        version: ">=1.0.0"
        communication: rest
        
    external:
      - service: lexisnexis
        type: risk_data
        protocol: soap
        retry: 3
        
      - service: experian
        type: credit_data
        protocol: rest
        retry: 3

deployment:
  container:
    base_image: python:3.11-slim
    health_check:
      endpoint: /health
      interval: 30s
      
  kubernetes:
    namespace: insurance
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 4000m
        memory: 8Gi
        
    gpu_support:
      enabled: true
      type: nvidia-t4
      count: 2
      
  environment_variables:
    - name: MODEL_SERVER_URL
      secret: true
    - name: RULE_ENGINE_CONFIG
      configmap: true
    - name: ML_MODEL_PATH
      default: /models